schema_version: 1

context:
  name: cuda_histogram
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 3f99db39407be0538ad4159789f5e6944e3e705d3f878f4f4eb61fdca5ff808d

build:
  number: 0
  skip: win or osx
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - awkward >=2.6.3
    - cupy >=13.6.0
    - numpy >=1.22.0
    - hist >=2
    - boost-histogram

tests:
  - python:
      imports:
        - cuda_histogram
        - cuda_histogram.axis
      pip_check: true

about:
  summary: Histogramming tools on CUDA
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/cuda-histogram
  documentation: https://cuda-histogram.readthedocs.io/

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - Saransh-cpp
